parameters:
    ongr_connections.extractor.passthrough_extractor.class: ONGR\ConnectionsBundle\Sync\Extractor\PassthroughExtractor
    ongr_connections.sync.relations_collection.class: ONGR\ConnectionsBundle\Sync\Extractor\Relation\RelationsCollection

services:
    ongr_connections.sync.extractor.doctrine_extractor:
        class: ONGR\ConnectionsBundle\Sync\Extractor\DoctrineExtractor
        calls:
            - [ setRelationsCollection, [ @ongr_connections.sync.relations_collection ] ]
            - [ setConnection, [ @database_connection ] ]
            - [ setStorageFacility, [ @ongr_connections.sync.panther ] ]

    ongr_connections.sync.extractor.passthrough_extractor:
        class: %ongr_connections.extractor.passthrough_extractor.class%
        calls:
            - [ setStorageFacility, [ @ongr_connections.sync.panther ] ]

    ongr_connections.sync.relations_collection:
        class: %ongr_connections.sync.relations_collection.class%
