parameters:
    ongr_connections.extractor.doctrine_extractor.class: ONGR\ConnectionsBundle\Sync\Extractor\DoctrineExtractor
    ongr_connections.extractor.passthrough_extractor.class: ONGR\ConnectionsBundle\Sync\Extractor\PassthroughExtractor
    ongr_connections.sync.extraction_collection.class: ONGR\ConnectionsBundle\Sync\Extractor\Descriptor\ExtractionCollection

services:
    ongr_connections.sync.extractor.doctrine_extractor:
        class: %ongr_connections.extractor.doctrine_extractor.class%
        calls:
            - [ setExtractionCollection, [ @ongr_connections.sync.extraction_collection ] ]
            - [ setConnection, [ @?database_connection ] ]
            - [ setStorageFacility, [ @ongr_connections.sync.sync_storage ] ]
            - [ setContainer, [ @service_container ] ]

    ongr_connections.sync.extractor.passthrough_extractor:
        class: %ongr_connections.extractor.passthrough_extractor.class%
        calls:
            - [ setStorageFacility, [ @ongr_connections.sync.sync_storage ] ]
            - [ setContainer, [ @service_container ] ]

    ongr_connections.sync.extraction_collection:
        class: %ongr_connections.sync.extraction_collection.class%
